# TODO: May not work with derivitaves
# - see https://docs.docker.com/engine/install/debian/#install-using-the-repository
# - set_fact for codename and use that instead of ansible_distribution?
---
- name: Remove unofficial Docker packages
  ansible.builtin.package:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Add Docker prerequisites
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
    state: present

- name: Add Docker apt GPG Key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: Set architecture
  ansible.builtin.set_fact:
    arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ('arm64' if
      ansible_architecture == 'aarch64' else ansible_architecture) }}"

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker
